### ISSUE TITLE
ux: timeline aktive fläche vergrößern

### ISSUE THREAD

**Issue by vmucha** [stroeer/video#11]
https://t-online.atlassian.net/browse/ENGAGE-1082

**Comment by jrsmb** [comment]
PR:
Increase timeline hover area
https://github.com/stroeer/stroeer-videoplayer-default-ui/pull/25

**Comment by jrsmb** [comment]
Branch can now be checked out, code ready for review

**Comment by jrsmb** [comment]
Tag v3.1.0 released mit der neuen seekbar: https://github.com/stroeer/stroeer-videoplayer-default-ui/releases/tag/v3.1.0
