### ISSUE TITLE
pausieren bei tabwechsel nur werbung läuft.

### ISSUE THREAD

**Issue by vmucha** [stroeer/video#12]
https://t-online.atlassian.net/browse/ENGAGE-3925
beim livestream war das super nervig, den würde ich gern im inaktiven tab weiter"hören".

**Comment by ennoStroeer** [comment]
PR's:
https://github.com/stroeer/stroeer-videoplayer/pull/39
https://github.com/stroeer/stroeer-videoplayer-ima-plugin/pull/21
https://github.com/stroeer/stroeer-videoplayer-ivad-plugin/pull/3

**Comment by walialu** [comment]
Review done :smiley:

**Comment by walialu** [comment]
Ist heute live gegangen
