### ISSUE TITLE
Clicktoplay does not start the IMA ad to play (mobile devices)

### ISSUE THREAD

**Issue by evaschmuhl** [stroeer/video#13]
Because of _The browser prevented playback initiated without user interaction_ the IMA gets errors, that the ad could not have been played (400 / 900).

This happens mostly on iOS devices. Marco had a solution, that the ima plugin might lay a container over the player, that gets the user video play click and gives it to the ima to start the ad.

**Comment by MarvinRuppelt** [comment]
Thema Autoplay noch offen

**Comment by ennoStroeer** [comment]
Autoplay ist jetzt auch fixed
