### ISSUE TITLE
Vorschauscreen der Seekbar soll nicht im Startscreen aktiv sein

### ISSUE THREAD

**Issue by MicLicht** [stroeer/video#18]
IST: Bei Mouseover über den noch nicht gestarteten Player wird in der Seekbar der Vorschauscreen angezeigt und erzeugt über das Laden weiterer Video-Chunks im Hintergrund Traffic.

SOLL: Der Vorschauscreen der Seekbar soll im Startscreen nicht aktiv sein,

**Comment by evaschmuhl** [comment]
Fixed in Default UI Version 3.0.1
