### ISSUE TITLE
hls.js wird auf allen browsern geladen und genutzt 

### ISSUE THREAD

**Issue by max-dombrowski** [stroeer/video#24]
Da wir das native HLS nicht konfigurieren können, ist es uns nicht möglich eine Buffersize zu setzen. Das führt zu deutlich erhöhten und unerwünschten Video-Traffic. 

# AK
- [ ] hls.js wird auf allen browsern geladen und genutzt 
- [ ] die hls config entspricht https://github.com/stroeer/video/blob/dd69a5a7bec6ad126416f4a9dececfeb30234752/packages/player/src/StroeerVideoplayer.ts#L112-L114 

# How to test
- [ ] OnPlay werden nur die aktuell benötigen Chunks (Networktab nach .ts filtern) geladen

**Comment by walialu** [comment]
![image](https://user-images.githubusercontent.com/1384938/207035509-79ca60df-7894-41c7-8d19-46f2b5cedb15.png)
![image](https://user-images.githubusercontent.com/1384938/207036117-7fcfecf8-e32c-4405-bafd-cb8b17ded3c5.png)
