### ISSUE TITLE
BUG: Tonpatzer in diversen Video durch ggf. Transcoding oder Qualitätswechsel

### ISSUE THREAD

**Issue by MicLicht** [stroeer/video#5]
Uns sind in diversen Stücken Tonspratzer aufgefallen nach 5,6 Sekunden Laufzeit. Diese sind aber nicht im Schnittprogramm, sondern nur live zu hören. Hängt ggf. (als Tipp/Erklärungsansatz von Arno) damit zusammen, wenn sich die Bildqualität automatisch umstellt im Player. Taucht auch nicht immer auf, aber ist eben punktuell zu hören.

Könnt ihr das bitte BUZZ zwecks Transcoding checken lassen und Engagement zwecks Player.

Hier mal vier Beispiele:
https://www.t-online.de/nachhaltigkeit/energie/id_100062390/energiekrise-stromtricks-so-sparen-sie-50-prozent-ohne-sich-umzugewoehnen.html
https://www.t-online.de/tv/unterhaltung/id_92443286/madonna-kaum-wiederzuerkennen-ist-das-ihr-coming-out-.html
https://www.t-online.de/nachrichten/ukraine/id_100060982/-wir-kaempfen-gegen-satanismus-in-seiner-reinsten-form-.html
https://www.t-online.de/nachrichten/ukraine/id_100054488/russische-haeftlinge-werben-fuer-den-einsatz-im-ukraine-krieg-warten-auf-euch-.html

**Comment by MicLicht** [comment]
Gibt auch ein Ticket bei TOL https://t-online.atlassian.net/browse/ENGAGE-4039

Enno hat das HLS.js auf den neusten Stand gebracht, hat aber leider nix gebracht

**Comment by ennoStroeer** [comment]
Folgendes habe ich probiert:
- auf lokaler Testseite o.g. Video in den videoplayer geladen, keine Tonprobleme
- alle Qualitäten einzeln in einem Mediaplayer aufgerufen, ebenfalls ohne Befund
- Qualitätswechsel bei laufendem Video per Console forciert: Keine Tonprobleme

Mir ist aufgefallen, dass lokal mit anderen Qualitäten gearbeitet wird, daher wäre interessant, mit welcher hls config die t-online da ins Rennen geht

**Comment by ennoStroeer** [comment]
Weitere Analysen ergeben keine Regelmäßigkeiten, also es tritt vollkommen erratisch ohne Abhängigkeit von Qualität, Browser, Transcoding (nochmal transcodiert) oder so auf.

Ich habe jetzt einfach mal den revolverplay ne Weile durchlaufen lassen, manchmal kommt der tonpatzer, manchmal nicht, wenn dann immer nach ca. 5s.

Ich sehe allerdings in der console ebenfalls sporadisch geblockte Files aus dem stream, sowohl .m3u8 als auch .ts Dateien, wahrscheinlich fehlt der cors header, z.b.:
![grafik](https://user-images.githubusercontent.com/67469694/196995930-758fef94-5d7c-4949-bf8c-a0d42d5a1718.png)

**Comment by walialu** [comment]
Fuer mich sieht es danach aus, als ob das durch HOMAD verursacht wird, ganz sicher bin ich mir zwar nicht, aber es ist schon sehr merkwuerdig, dass ich das in einem Setup ohne HOMAD eigentlich nie nachgestellt bekomme, wenn HOMAD aktiviert ist, allerdings dauernd.

Hat @stroeer/buzz denn mittlerweile den HOMAD Switch eingebaut, sodass wir das mal fix ohne HOMAD testen koennten?

**Comment by bobaaaaa** [comment]
Ja es gibt den homad switch. Der ist aber global, also für alle Videos.

**Comment by walialu** [comment]
Nice @bobaaaaa, ich kläre am Montag mal mit @MicLicht, ob wir Homad mal testweise ausknippsen dürfen und melde mich dann per Slack bei dir, ja?

**Comment by walialu** [comment]
Das ist die Stelle: https://github.com/stroeer/stroeer-videoplayer/blob/main/src/StroeerVideoplayer.ts#L440

Wenn ich hier ein

```js
const hls = new HlsJs()
```

draus mache, tritt der Tonpatzer nicht mehr auf.

Montag gucke ich mir das genauer an.

**Comment by walialu** [comment]
Es liegt an der default Option die von uns gesetzt wird:

```
capLevelToPlayerSize: true
```

wenn ich die hier auf `false` setze, habe ich keine Tonpatzer mehr.

https://github.com/stroeer/paper/blob/eaaab4580ab54a5946b68cf127c47dce470c5613/packages/ui-library/src/components/ElementVideoPlayerStroeer/useVideoPlayer.ts#L96

statt

```js
const videoPlayer = new StroeerVideoPlayer(currentVideoRef);
```

quasi sowas hier:

```js
const videoPlayer = new StroeerVideoPlayer(currentVideoRef, {capLevelToPlayerSize: false});
```
