### ISSUE TITLE
BUG VPaid Player hängt sich auf

### ISSUE THREAD

**Issue by MicLicht** [stroeer/video#6]
IST: es kommen aktuell viele VPaids, die als Spot mit schwarzem Bild angezeigt werden, oder das PosterImage zeigen und den Ton abspielen. Der Content im Anschluss wird nicht abgespielt und es wird der Ladespinner die ganze Zeit angezeigt. 

Beispiele als Video siehe Slack
https://stroeerpublishing.slack.com/archives/C02JAGGBF37/p1667491931569369
https://stroeerpublishing.slack.com/archives/C02JAGGBF37/p1667569904691639

Hier zwei Testspots von SDI

https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_ad_samples&sz=640x480&cust_params=sample_ct%3Dnonlinearvpaid2js&ciu_szs=728x90%2C300x250&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=

https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_ad_samples&sz=640x480&cust_params=sample_ct%3Dlinearvpaid2js&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator=

SOLL: Werbung und Video soll korrekt abgespielt werden.

**Comment by MicLicht** [comment]
Velux Kampange 
https://gcdn.2mdn.net/api/manifest/hls_variant/source/web_video_ads/id/a0d8f3d808df1459/itag/0/playlist_type/LIVE/ei/m30QY7ncLcTm4QSyw6iIDQ/susc/vsau/acao/yes/ctier/L/vprv/1/pacing/0/ip/0.0.0.0/ipbits/0/expire/3806473115/sparams/ip,ipbits,expire,source,id,itag,playlist_type,ei,susc,acao,ctier,vprv/signature/E74D0E6F45D566A97F8C4CB901118354253A4189F76543A7DC457592776EEDDF.610971ABCCD6C63C8C7CADBD61D06B3F75FF9F832453DF1407748AF1993814E9/key/us0/file/index.m3u8

**Comment by MicLicht** [comment]
ist @walialu dran [4170](https://t-online.atlassian.net/browse/ENGAGE-4170)

**Comment by walialu** [comment]
Fix ist live.
